#! /bin/bash

####################################################################################
#
#                                      Huggin API
#
####################################################################################

#############
# 12/7/24 DH: Get output of training (incl non-token logits unavailable in non-training run)
#############

# 16/7/24 DH: Copy from 'get-model-output'
SCRIPTDIR=$(dirname "$0")
SCRIPTNAME=$(basename "$0")
CWD=$(pwd)

# TODO: Decide if this should be hard-coded across mutliple files (as currently is)
CFGDIR="/Users/doug/src/ai/t5"
HFOUTDIR="previous_output_dir-Google-BERT"

#JSONCFG="qa_train-Google-BERT-custom.json"
JSONCFG="qa_train-Google-BERT-SQUAD.json"

# 9/7/24 DH: Now moving from SCRIPTDIR to CWD
QArunTLD="${CWD}/${HFOUTDIR}"
WEIGHTSDIR="${QArunTLD}/weights"

# 9/7/24 DH: Prev used SCRIPTDIR but better to use 'cwd' (which gets propagated)
mkdir -p ${CWD}/gv-graphs
echo "CREATED: 'gv-graphs' IN: '${CWD}'"
echo

echo
echo "--------------- SCRIPT PARAMS ------------------"
echo "                -------------"
echo "Model TLD:  '${QArunTLD}'"
echo "Run cfg:     ${JSONCFG}"
echo "Output dir: '${CWD}'"
echo "------------------------------------------------"
echo

counter=0

# ======================================= INDIV SCRIPTS ================================================
# --------------------------------- TRAINING RUN -------------------------------
let counter++
echo "${counter}) run_qa.py"
echo "------------"

python ${SCRIPTDIR}/run_qa.py ${CFGDIR}/${JSONCFG}
# 8/7/24 DH: Save "$?" since it changes after the conditional "test"
retVal=$?

echo
#echo "Exiting script during dev..."
#exit

# --------------------------------- GRAPH TRAINING WEIGHTS + LOSSES -------------------------------
let counter++
echo "${counter}) graph-weights.py"
echo "-------------------"

#python ${SCRIPTDIR}/graph-weights.py ${WEIGHTSDIR} show &
# 21/7/24 DH: Need sleep for BG process so that print output correlates with heading
#sleep 2

# 13/8/24 DH: 'graph-weights.py' copies 'weights-full.log' to 'weights-full-0.log' if it contains "0-Start: ..."
python ${SCRIPTDIR}/graph-weights.py ${WEIGHTSDIR}
echo

# 21/6/24 DH: Add 'graph-losses.py'
let counter++
echo "${counter}) graph-losses.py"
echo "------------------"

#python ${SCRIPTDIR}/graph-losses.py ${WEIGHTSDIR} show &
# 21/7/24 DH: Need sleep for BG process so that print output correlates with heading
#sleep 2

python ${SCRIPTDIR}/graph-losses.py ${WEIGHTSDIR}
echo

# --------------------------------- GRAPH TRAINING LOGITS -----------------------------
# 18/7/24 DH: Readded 'huggin_utils::logLogits(...)' to 'BertForQuestionAnswering.forward()'
#             (as commented in 'huggin_utils::logLogits(...)')
#             (to get non-token logits unavailable in non-training run)
let counter++
echo "${counter}) graph-logits.py"
echo "------------------"

#python ${SCRIPTDIR}/graph-logits.py ${QArunTLD} show
python ${SCRIPTDIR}/graph-logits.py ${QArunTLD}
echo

# --------------------------------- PRODUCE GRAPHVIZ PDF -------------------------------
let counter++
echo "${counter}) create-gv-training.py"
echo "------------------------"

python ${SCRIPTDIR}/create-gv-training.py ${HFOUTDIR}
retVal=$?
if [ ${retVal} -ne 0 ]; then
  echo
  echo "Error in 'create-gv-training.py' so exiting..."
  echo
  exit
fi

# 1/7/24 DH: Remove 'quarantine' file extended attribute
xattr -c $(cat gvTrain_filename.txt)

open $(cat gvTrain_filename.txt)

